// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PuppyToy.Services.DataAccess;

#nullable disable

namespace PuppyToy.Services.Migrations
{
    [DbContext(typeof(PuppyToyContext))]
    [Migration("20220727133728_Sessions")]
    partial class Sessions
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.7");

            modelBuilder.Entity("PuppyToy.Models.Storable.EmlalockFeedItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ActionType")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("EmlalockSessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PupDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("TimeDelta")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TimeUnit")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmlalockSessionId");

                    b.ToTable("EmlalockFeedItems");
                });

            modelBuilder.Entity("PuppyToy.Models.Storable.EmlalockSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("EmlalockSessions");
                });

            modelBuilder.Entity("PuppyToy.Models.Storable.EmlalockFeedItem", b =>
                {
                    b.HasOne("PuppyToy.Models.Storable.EmlalockSession", null)
                        .WithMany("FeedItems")
                        .HasForeignKey("EmlalockSessionId");
                });

            modelBuilder.Entity("PuppyToy.Models.Storable.EmlalockSession", b =>
                {
                    b.Navigation("FeedItems");
                });
#pragma warning restore 612, 618
        }
    }
}
